---
title: "Easy Mac and Cheese with bread crumbs "
format: html
editor: visual
---

Total time: Less than 20 minutes

## Tools needed:

 - Noodle pot

 - Non-stick skillet 
 
## Ingredients:

- 1 boxed mac and cheese (with butter and milk or pasta water)

- 1/2 cup Panko bread crumbs 

- 1/4 cup grated Parmesan cheese

- 1/2 TBSP Olive oil

- Extra shredded cheese (optional)

- Cajun Seasoning

## Instructions:

1.  **Cook noodles:**: For 7 oz noodles, add 2 quarts (8 cups) water and 3/4 TBSP salt to pot and bring to a boil. Add noodles and re-cover to bring back to a boil. Cook noodles according to the box. 

2. **Make breadcrumbs**: Toast bread crumbs in large nonstick skillet over medium-high heat until browned, about 5 minutes. Transfer to bowl. Toss with 1 tablespoon olive oil, 1/4 cup Parmesan. 

3. **Combine**: Once the noodles are done, add extra cheese if using, cajun seasoning and stir. Finish with bread crumbs prior to serving. 

4. **Buffalo Chicken Variant**: If you have frozen or left over chicken, you can reheat it in a skillet with buffalo sauce and around a 1 tbsp butter and add to the top.
