---
title: "Chicken breast in a creamy white wine pan sauce"
format: html
editor: visual
---

Total time: Probably like 30 minutes

Use a stick pan for this one.

## Ingredients

-   2 (12 oz) boneless skinless chicken breasts

-   1 Tbsp olive oil

-   4 Tbsp Danish Creamery European Style Unsalted Butter, cut into 1 Tbsp pieces, divided

-   1 cup finely chopped yellow onion (1 small) OR shallot

-   2 tsp minced garlic (2 cloves)

-   1 1/4 cups + 1 Tbsp low-sodium chicken broth, divided

-   1/4 cup heavy cream (sub with 1/4 cup broth if not desired)

-   1 cup dry white wine, recommend Sauvigon Blanc

-   2 tsp thyme leaves or tarragon

-   1.5 tsp cornstarch

-   1 Tbsp minced fresh parsley

## Instructions

1.  **Season chicken breasts:** : Trim, dry, and season the chicken breasts with paprika, salt, pepper and garlic powder. Rub the spices in and distribute it as evenly as possible. Don't be afraid of the paprika.

2.  **Cook chicken breasts:** Heat oil in a 12-inch skillet over medium-high heat.Place chicken in skillet (spacing evenly apart) and cook until browned and cooked through, about 4 to 5 minutes per side (chicken should register 165 degrees in center of thickest portion). Note that if skillet seems dry when you turn chicken to second side then drizzle in an additional 1/2 Tbsp olive oil. Transfer chicken to a plate and cover with aluminum foil to keep warm.

3.  **Make pan sauce:** Return skillet to medium heat. Add 2 Tbsp butter and stir to melt. Add onions and saute until tender and golden brown, about 5 minutes. Add garlic and saute 30 seconds longer. Slowly pour in 1 1/4 cups chicken broth and the white wine while scraping up browned bits from the bottom of the pan. Stir in thyme or tarragon leaves. Bring to a simmer, then reduce heat to medium-low and let simmer until alcohol flavor has cooked off and sauce has reduced to about 1/3 it's original volume, about 12 - 15 minutes.

4.  **Create thickener for sauce:** In a small bowl whisk together remaining 1 Tbsp chicken broth with cornstarch until smooth. Once sauce in skillet has reduced stir in the cornstarch mixture and cook until thickened, while whisking, about 1 minute longer.

5.  **Finish sauce**: Melt remaining 2 Tbsp butter in sauce and add cream if using. Season sauce with salt if needed and pepper to taste. Return chicken to sauce in skillet, spoon sauce over and sprinkle with parsley and serve.
