---
title: "Chocolate Chip Cookies"
format: html
editor: visual
---

Total time: 30 minutes

# Ingredients

-   1 3/4 cups unbleached all-purpose flour (8 3/4 ounces; 250g)

-   1/2 teaspoon baking soda (3g or so)

-   14 tablespoons unsalted butter (1 3/4 sticks; 200g) 

-   1/2 cup granulated sugar (3 1/2 ounces; 100g)

-   3/4 cup packed dark brown sugar (5 1/4 ounces; 150g) (see note)

-   1 teaspoon table salt (6g or so)

-   2 teaspoons vanilla extract

-   1 large egg

-   1 large egg yolk

-   1 1/4 cups *semisweet chocolate chips or chunks* (200g, used 52% cacao chips)

-   3/4 cup chopped pecans or walnuts

Note: The brand of chocolate chips is important. Bad ones stick out pretty obviously. I've used Ghirardelli 60% cacao and 72%. Both are okay, but the 72% can be a little bitter.

# Instructions

1.  **Preheat oven and combine dry ingredient:s** Adjust oven rack to middle position and heat oven to 375 degrees F 190 C. Line 2 large (18- by 12-inch) baking sheets with parchment paper. Whisk flour and baking soda together in medium bowl; set aside.

2.  **Brown the butter:** Heat 10 tablespoons butter (140g. ) in 10-inch skillet over medium-high heat until melted, about 2 minutes. Continue cooking, swirling pan constantly until butter is dark golden brown and has nutty aroma, 1 to 3 minutes. Remove skillet from heat and, using heatproof spatula, transfer browned butter to large heatproof bowl. Stir remaining 4 tablespoons butter into hot butter until completely melted.

3.  **Combine ingredients and whisk:** Add both sugars, salt, and vanilla to bowl with butter and whisk until fully incorporated. Add egg and yolk and whisk until mixture is smooth with no sugar lumps remaining, about 30 seconds. Let mixture stand 3 minutes, then whisk for 30 seconds. Repeat process of resting and whisking 2 more times until mixture is thick, smooth, and shiny.

4.  **Add flour mixture and chocolate chips:** Using rubber spatula or wooden spoon, stir in flour mixture until just combined, about 1 minute. Stir in chocolate chips and nuts (if using), giving dough final stir to ensure no flour pockets remain.

5.  **Make balls of dough:** Divide dough into 16 portions, each about 3 tablespoons (or use #24 cookie scoop). Arrange 2 inches apart on prepared baking sheets, 8 dough balls per sheet. (Smaller baking sheets can be used, but will require 3 batches.)

6.  **Bake:** Bake cookies 1 tray at a time until cookies are golden brown and still puffy, and edges have begun to set but centers are still soft, 10 to 14 minutes, rotating baking sheet halfway through baking. Transfer baking sheet to wire rack; cool cookies completely before serving.
