---
title: "Grandma's Pound Cake"
format: html
editor: visual
---

Total time: Depends! 1-2 hours

Note: to be baked beginning in a cold oven, do not preheat

Makes 2 loaves or 1 bundt cake.

## Ingredients

-   3 cups of sugar (21 ounces)

-   3 cups cake flour (12 ounces - sifted: measure out 3 cups from box then sift)

-   1/2 teaspoon baking powder

-   1 teaspoon vanilla extract

-   1/2 cup Crisco Shortening

-   5 eggs (room temperature)

-   2 sticks of butter (melted)

-   1 cup milk (room temperature)

## Instructions

1.  **Make cream mixture**: Blend melted butter, sugar and crisco until smooth. Add eggs one at a time, blend batter after each egg addition.

2.  **Make flour mixture**: Combine sifted cake flour and baking powder.

3.  **Combine mixtures**: Slowly add the flour mixture to the cream mixture, fully stirring in each addition of the flour mixture before adding more.

4.  **Add dairy and finish batter**: Add milk and vanilla extract. Beat batter until smooth. Pour into cake pan. Start in cold oven.

5.  **Add to greased pans and bake**: Add batter to 2 greased loafpans or a greased bundt pan. Start in cold oven and set to 350. Baking times vary: 1h 20m for a bundt cake and start at \~20 minutes for a loaf cake.

6.  **Remove from pan to let cool**: Let cake cool for no more than 5 minutes and remove from pan.

## SWEET VANILLA FROSTING (version 1)

-   3 cups powdered/confectioner's sugar

-   1⁄3 cup butter (softened to room temperature)

-   1 1⁄2 teaspoons real vanilla extract

-   1 to 2 tablespoons of milk

Mix powdered sugar and softened butter with a mixer on low speed. Stir in vanilla & 1 tablespoon of milk. Gradually add enough milk (a drop or two at a time) to make frosting smooth & spreadable. If frosting appears to thin then add more powdered sugar. Mix on medium or high speed to make frosting fluffy.


## VANILLA BUTTER CREAM (version 1)

-   2 cups powdered/confectioner's sugar

-   1 stick of butter

-   1 teaspoon vanilla

-   2 tablespoons of milk

Mix powdered sugar and softened butter with a mixer on low speed. Stir in vanilla & 1 tablespoon of milk. Gradually add enough milk (a drop or two at a time) to make frosting smooth & spreadable. If frosting appears to thin then add more powdered sugar. Mix on medium or high speed to make frosting fluffy.
