---
title: "Spaghetti with Meat Sauce"
format: html
editor: visual
---

Total time: 1 hour(ish)

## Ingredients

-   1 pound (500g) ground meat (beef, turkey or other)

-   7-8 ounces (200g) Tomato Sauce

-   12 ounces (340g) Tomato Paste

-   400ml beef broth

-   1 medium onion, diced (yellow or white)

-   3-4 garlic gloves, minced

-   1 tbsp oregano

-   1 tbsp dried basil

-   1 Bay leaf

-   1 tsp Soy sauce

-   1 tsp sugar

-   Parmesan cheese for serving

-   Olive Oil/Butter

-   Salt/pepper

## Instructions

1.  **Cook aromatics**: In a dutch oven or a pot of choice, add oil over medium heat. When hot, add onions cook until slightly translucent and softened (around 5-7 minutes). Then add garlic and cook until fragrent (1 minute).

2.  **Add and cook meat**: Add ground meat and cook, breaking apart with a wooden spoon until no longer pink and broken up into several smaller pieces. Drain the fat.

3.  **Add tomato paste and spices**: Add the tomato paste, basil and oregano and allow mix into the meat and aromatics. Cook for a minute or so.

4.  **Hydrate the tomato paste with broth and add other stuff**: Add beef broth and stir, then add the tomato sauce, sugar, bay leaf, soy sauce. Taste the sauce at this point and add salt if it tastes bland (if it's slightly salty remember that simmering it will concentrate the flavor, so be careful not to add too much). Add black pepper (or red pepper if you prefer), to bring the "spice" level to balance. It should not taste spicy, but if you feel something is missing at this taste test, it might be pepper (or spice).

5.  **Simmer!**: Now it is time to let the sauce simmer. Ideally, you will do this for a minumum of 30 minutes. You can leave it covered, partially covered, or uncovered, but make sure the simmer is gentle (few bubbles, not like a boil). The purpose of this is to a) continue to soften the onions and meat and b) to allow the flavors to concentrate and come together.

6.  **Taste and make final adjustments**: For every 30 or so minutes of simmering, repeat the taste test and adjust as needed. Shred parm and serve!
